title: "QinCodec: Neural Audio Compression with Implicit Neural Codebooks"
github: [metadata]

remote_theme: pages-themes/cayman@v0.2.0
url: https://accompanying-website.xyz # https://github.com/zinebl-sony/post-training-rvq\
baseurl: ""
repository: zinebl-sony/post-training-rvq

markdown: kramdown
kramdown:
    math_engine: katex
    syntax_highlighter: rougify

plugins:
    - jekyll-remote-theme